package io.openems.edge.evse.chargepoint.abl;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evse.chargepoint.abl.enums.AblEMh1HardwareType;
import io.openems.edge.evse.chargepoint.abl.enums.LogVerbosity;
import io.openems.edge.meter.api.PhaseRotation;

@ObjectClassDefinition(//
		name = "EVSE Charge-Point ABL eMH1", //
		description = "ABL eMH1 series electric vehicle charging station (Modbus/ASCII).")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evseChargePoint0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read only", description = "Prevents any write commands to the device. Monitoring only.", required = true)
	boolean readOnly() default false;

	@AttributeDefinition(name = "Hardware type", description = "ABL eMH1 product variant. Determines phase count and maximum current.", required = true)
	AblEMh1HardwareType hardwareType() default AblEMh1HardwareType.EMH1_3P_22KW_CABLE;

	@AttributeDefinition(name = "Phase Rotation", description = "Apply standard or rotated phase wiring (L1/L2/L3 mapping)")
	PhaseRotation phaseRotation() default PhaseRotation.L1_L2_L3;

	@AttributeDefinition(name = "Fallback Voltage L1 [V]", description = "Phase voltage L1 used when no channel address is configured or the channel is unavailable.")
	int fallbackVoltageL1() default 230;

	@AttributeDefinition(name = "Fallback Voltage L2 [V]", description = "Phase voltage L2 used when no channel address is configured or the channel is unavailable.")
	int fallbackVoltageL2() default 230;

	@AttributeDefinition(name = "Fallback Voltage L3 [V]", description = "Phase voltage L3 used when no channel address is configured or the channel is unavailable.")
	int fallbackVoltageL3() default 230;

	@AttributeDefinition(name = "Voltage L1 Channel Address", description = "Optional: channel address to read live phase voltage L1 (e.g. 'meter0/VoltageL1'). Leave empty to use fallback voltage.")
	String voltageL1ChannelAddress() default "";

	@AttributeDefinition(name = "Voltage L2 Channel Address", description = "Optional: channel address to read live phase voltage L2. Leave empty to use fallback voltage.")
	String voltageL2ChannelAddress() default "";

	@AttributeDefinition(name = "Voltage L3 Channel Address", description = "Optional: channel address to read live phase voltage L3. Leave empty to use fallback voltage.")
	String voltageL3ChannelAddress() default "";

	@AttributeDefinition(name = "Enable upstream timeout", description = "Write 0x9001 to register 0x002C on startup: enables hardware upstream-timeout (F4) and configures auto B1→B2 transition. Recommended: true.")
	boolean enableUpstreamTimeout() default true;

	@AttributeDefinition(name = "Log verbosity", description = "Controls diagnostic logging level.")
	LogVerbosity logVerbosity() default LogVerbosity.NONE;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge component")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "Modbus unit-ID of the ABL device (default: 1 for single-outlet setup). Also used as device-ID field [7:0] when writing register 0x002C.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EVSE Charge-Point ABL eMH1 [{id}]";
}
